const players = [
  {
    name: "Lionel Messi",
    team: "Paris Saint-Germain",
    nationality: "Argentinian",
    jerseyNumber: 30,
    age: 34,
    imageURL: "https://a.espncdn.com/combiner/i?img=/i/headshots/soccer/players/full/45843.png&w=350&h=254",
  },
  {
    name: "Cristiano Ronaldo",
    team: "Manchester United",
    nationality: "Portuguese",
    jerseyNumber: 7,
    age: 37,
    imageURL: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Persepolis%2C_September_2023_%28cropped%29.jpg/250px-Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Persepolis%2C_September_2023_%28cropped%29.jpg",
  },
  {
    name: "Neymar Jr",
    team: "Paris Saint-Germain",
    nationality: "Brazilian",
    jerseyNumber: 10,
    age: 30,
    imageURL: "https://icdn.psgtalk.com/wp-content/uploads/2020/08/Neymar-training-PSG-vs-Bayern-Munich-Champions-League-2020.jpg",
  },
  {
    name: "Kylian Mbappe",
    team: "Paris Saint-Germain",
    nationality: "French",
    jerseyNumber: 7,
    age: 23,
    imageURL: "https://s.hs-data.com/bilder/spieler/gross/284095.jpg",
  },
    {
      name: "Robert Lewandowski",
      team: "Bayern Munich",
      nationality: "Polish",
      jerseyNumber: 9,
      age: 33,
      imageURL: "https://cdn-europe1.lanmedia.fr/var/europe1/storage/images/europe1/sport/coupe-du-monde-2022-attention-a-robert-lewandowski-pour-les-bleus-4151618/59460103-1-fre-FR/Coupe-du-monde-2022-attention-a-Robert-Lewandowski-pour-les-Bleus.jpg",
    },
    {
      name: "Kevin De Bruyne",
      team: "Manchester City",
      nationality: "Belgian",
      jerseyNumber: 17,
      age: 30,
      imageURL: "https://imgresizer.eurosport.com/unsafe/1200x0/filters:format(jpeg)/origin-imgresizer.eurosport.com/2024/01/13/3860923-78451388-2560-1440.jpg",
    },
    {
      name: "Sadio Mané",
      team: "Liverpool",
      nationality: "Senegalese",
      jerseyNumber: 10,
      age: 29,
      imageURL: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Sadio_Man%C3%A9_-_Persepolis_F.C._v_Al_Nassr_FC%2C_19_September_2023.jpg",
    },
    {
      name: "Mohamed Salah",
      team: "Liverpool",
      nationality: "Egyptian",
      jerseyNumber: 11,
      age: 29,
      imageURL: "https://resources.premierleague.com/premierleague/photos/players/250x250/p118748.png",
    },
    {
      name: "Harry Kane",
      team: "Tottenham Hotspur",
      nationality: "English",
      jerseyNumber: 10,
      age: 28,
      imageURL: "https://icdn.psgtalk.com/wp-content/uploads/2020/08/Neymar-training-PSG-vs-Bayern-Munich-Champions-League-2020.jpg",
    },
    {
      name: "Luis Suárez",
      team: "Atlético Madrid",
      nationality: "Uruguayan",
      jerseyNumber: 9,
      age: 35,
      imageURL: "https://www.fcbarcelona.com/fcbarcelona/photo/2020/09/06/c7355114-245c-48a3-b5fe-0cea11dc9379/SUAREZ-56-min.jpg",
    },
    {
      name: "Karim Benzema",
      team: "Real Madrid",
      nationality: "French",
      jerseyNumber: 9,
      age: 34,
      imageURL: "https://i.guim.co.uk/img/media/87d567aa2fb5072f8db4181ba46748275d6e161d/145_329_3124_1874/master/3124.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=61eb67ea166f9daedd7cdea9defe8614",
    },
    {
      name: "Gareth Bale",
      team: "Real Madrid",
      nationality: "Welsh",
      jerseyNumber: 11,
      age: 32,
      imageURL: "https://imageio.forbes.com/specials-images/imageserve/5ecec1c2938ec500060ab3ba/0x0.jpg?format=jpg&crop=1231,1232,x838,y159,safe&height=416&width=416&fit=bounds",
    },
  ];
  
  export default players;
  